//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMM.WPF.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Captions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Captions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WMM.WPF.Resources.Captions", typeof(Captions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply templates.
        /// </summary>
        public static string ApplyTemplates {
            get {
                return ResourceManager.GetString("ApplyTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home economics.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        public static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average.
        /// </summary>
        public static string Average {
            get {
                return ResourceManager.GetString("Average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to month view.
        /// </summary>
        public static string BackToGoalMonths {
            get {
                return ResourceManager.GetString("BackToGoalMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category type.
        /// </summary>
        public static string CategoryType {
            get {
                return ResourceManager.GetString("CategoryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this category? This action cannot be undone..
        /// </summary>
        public static string ConfirmDeleteCategory {
            get {
                return ResourceManager.GetString("ConfirmDeleteCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this goal? This action cannot be undone..
        /// </summary>
        public static string ConfirmDeleteGoal {
            get {
                return ResourceManager.GetString("ConfirmDeleteGoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this transaction? This action cannot be undone..
        /// </summary>
        public static string ConfirmDeleteTransaction {
            get {
                return ResourceManager.GetString("ConfirmDeleteTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criteria.
        /// </summary>
        public static string Criteria {
            get {
                return ResourceManager.GetString("Criteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current.
        /// </summary>
        public static string Current {
            get {
                return ResourceManager.GetString("Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current month.
        /// </summary>
        public static string CurrentMonth {
            get {
                return ResourceManager.GetString("CurrentMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current.
        /// </summary>
        public static string CurrentValue {
            get {
                return ResourceManager.GetString("CurrentValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difference.
        /// </summary>
        public static string Difference {
            get {
                return ResourceManager.GetString("Difference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit entry.
        /// </summary>
        public static string EditTransaction {
            get {
                return ResourceManager.GetString("EditTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred: {0}.
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while opening thedata in Excel: {0}..
        /// </summary>
        public static string ExcelError {
            get {
                return ResourceManager.GetString("ExcelError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel is not installed on this machine.
        /// </summary>
        public static string ExcelNotInstalled {
            get {
                return ResourceManager.GetString("ExcelNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open forecast in Excel.
        /// </summary>
        public static string ExportForecastToExcel {
            get {
                return ResourceManager.GetString("ExportForecastToExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open search result in Excel.
        /// </summary>
        public static string ExportSearchToExcel {
            get {
                return ResourceManager.GetString("ExportSearchToExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forecast.
        /// </summary>
        public static string Forecast {
            get {
                return ResourceManager.GetString("Forecast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forecasts.
        /// </summary>
        public static string Forecasts {
            get {
                return ResourceManager.GetString("Forecasts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily.
        /// </summary>
        public static string ForecastTypeDaily {
            get {
                return ResourceManager.GetString("ForecastTypeDaily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception.
        /// </summary>
        public static string ForecastTypeException {
            get {
                return ResourceManager.GetString("ForecastTypeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly.
        /// </summary>
        public static string ForecastTypeMonthly {
            get {
                return ResourceManager.GetString("ForecastTypeMonthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recurring.
        /// </summary>
        public static string ForecastTypeRecurring {
            get {
                return ResourceManager.GetString("ForecastTypeRecurring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year overview.
        /// </summary>
        public static string GoalYears {
            get {
                return ResourceManager.GetString("GoalYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last month.
        /// </summary>
        public static string LastMonth {
            get {
                return ResourceManager.GetString("LastMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last week.
        /// </summary>
        public static string LastWeek {
            get {
                return ResourceManager.GetString("LastWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last year.
        /// </summary>
        public static string LastYear {
            get {
                return ResourceManager.GetString("LastYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit.
        /// </summary>
        public static string Limit {
            get {
                return ResourceManager.GetString("Limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage goals.
        /// </summary>
        public static string ManageGoals {
            get {
                return ResourceManager.GetString("ManageGoals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New area.
        /// </summary>
        public static string NewArea {
            get {
                return ResourceManager.GetString("NewArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New category.
        /// </summary>
        public static string NewCategory {
            get {
                return ResourceManager.GetString("NewCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No recurring.
        /// </summary>
        public static string NoRecurring {
            get {
                return ResourceManager.GetString("NoRecurring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only recurring.
        /// </summary>
        public static string OnlyRecurring {
            get {
                return ResourceManager.GetString("OnlyRecurring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        public static string Overview {
            get {
                return ResourceManager.GetString("Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recurring.
        /// </summary>
        public static string Recurring {
            get {
                return ResourceManager.GetString("Recurring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage recurring cost templates.
        /// </summary>
        public static string RecurringTitle {
            get {
                return ResourceManager.GetString("RecurringTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset all fields.
        /// </summary>
        public static string ResetAllFields {
            get {
                return ResourceManager.GetString("ResetAllFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select criteria.
        /// </summary>
        public static string SelectCriteria {
            get {
                return ResourceManager.GetString("SelectCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are transactions linked to the category you are deleting. Please select the category these transactions should be assigned to instead..
        /// </summary>
        public static string SelectFallbackCategory {
            get {
                return ResourceManager.GetString("SelectFallbackCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This month.
        /// </summary>
        public static string ThisMonth {
            get {
                return ResourceManager.GetString("ThisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This week.
        /// </summary>
        public static string ThisWeek {
            get {
                return ResourceManager.GetString("ThisWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This year.
        /// </summary>
        public static string ThisYear {
            get {
                return ResourceManager.GetString("ThisYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goals.
        /// </summary>
        public static string TitleMonthGoals {
            get {
                return ResourceManager.GetString("TitleMonthGoals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage monthly transactons for  {0} .
        /// </summary>
        public static string TitleRecurringMonth {
            get {
                return ResourceManager.GetString("TitleRecurringMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage categories.
        /// </summary>
        public static string TooltipCategories {
            get {
                return ResourceManager.GetString("TooltipCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check goals for this month.
        /// </summary>
        public static string TooltipGoalMonth {
            get {
                return ResourceManager.GetString("TooltipGoalMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage monthly transactions for this month.
        /// </summary>
        public static string TooltipRecurringMonth {
            get {
                return ResourceManager.GetString("TooltipRecurringMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yesterday.
        /// </summary>
        public static string Yesterday {
            get {
                return ResourceManager.GetString("Yesterday", resourceCulture);
            }
        }
    }
}
